### ISSUE TITLE
Build test slack app

### ISSUE THREAD

**Issue by nikeshashar** [makersacademy/fire_chief#1]
Our fire drill times are pretty good. The problem is that we're warned they are going to happen. In a real-world situation we would struggle to achieve results because ensuring we have adequate cover for all floors and each member of the fire-team understands what floor they are responsible for.

A slackbot that checks CharlieHR (like the rota bot) and notifies the fire team that they are on-duty and gets them to take ownership of an area in case of an incident. In the case of no fire-team members being in the building, the bot posts a note in #general.

**Comment by nikeshashar** [comment]
Setup a repo Firechief to push to Firechief Slack channel. Could build an MVP like Rotabot. Could build our own Slackbot, found a tutorial in Ruby which looks good to use.

**Comment by nikeshashar** [comment]
Currently following this tutorial to build the first app : https://github.com/slackapi/Slack-Ruby-Onboarding-Tutorial

**Comment by nikeshashar** [comment]
@roidriscoll and @nikeshashar paired on the initial SlackAPI tutorial, deployed a local bot (using ngrok). There is a test slackbot in place however we will be trialling a new tutorial that is more aligned with what we're trying to build for Firechief. 

@roidriscoll has also decided to go renegade and updated the firechief icon for the app.

**Comment by nikeshashar** [comment]
We're now trying this for learning further how Slackbots work  : https://www.sitepoint.com/building-a-slackbot-with-ruby-and-sinatra/

**Comment by rachelcdavies** [comment]
How far did you get?

**Comment by oceansize** [comment]
Spent far too long trying to debug a problem with the tutorial code, stripped back everything and had some success using the ruby slack client to send an incoming webhook to slack from the app which we deployed to heroku. Next step is to TDD the app because the code thus far is _horrible_, then once emoji reactions trigger the incoming webhook, we can integrate the google calendar API. This should take us to MVP. I suspect I will tinker with this a bit here and there over the holiday.

**Comment by oceansize** [comment]
Refactored tutorial code into separate files for easier editing. Might have to relegate this to spare time project as it is taking a long time to make progress.
